import Image from 'next/image';
import Link from 'next/link';
import { notFound, permanentRedirect } from 'next/navigation';
import type { Metadata } from 'next';
import { isLang, SITE_URL, EDITOR_NAME, EDITOR_ROLE, type Lang } from '@/lib/site';
import { authorNode, publisherNode } from '@/lib/schema';
import { getStrings } from '@/lib/i18n';
import { socialMeta } from '@/lib/seo';
import { getConceptNameIndex } from '@/lib/concepts';
import { markdownToPlainText } from '@/lib/markdown';
import {
  getAdjacentStories,
  getNewsItem,
  getPublishedItemPaths,
  getRelatedStories,
  youtubeVideoId,
} from '@/lib/items';
import { Breadcrumbs, breadcrumbJsonLd } from '@/components/breadcrumbs';
import { Byline } from '@/components/byline';
import { CategoryBadge } from '@/components/ui/category-badge';
import { CategoryBanner } from '@/components/category-banner';
import { StoryBody } from '@/components/story-body';
import { ItemShareBar } from '@/components/item-share-bar';
import { ItemEngagementTracker } from '@/components/item-engagement-tracker';
import { NewsletterForm } from '@/components/ui/newsletter-form';
import { VideoFacade } from '@/components/editorial/video-facade';
import styles from '@/components/article.module.css';
import { ArrowRight, ExternalLinkIcon } from '@/components/icons';

// 24 h: item content is fixed at publish; the editor-take edit revalidates the
// exact item path on-demand (see api/telegram handleEditorTake), so takes still
// appear immediately. The old 30 min window mostly fed bot-driven regenerations.
export const revalidate = 86400;

type Params = { lang: string; category: string; item: string };

export async function generateStaticParams() {
  return getPublishedItemPaths();
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { lang, category, item } = await params;
  if (!isLang(lang)) return {};
  const detail = await getNewsItem(category, item, lang);
  if (!detail) return {};
  if (detail.canonicalPath) {
    // The page normally 308s via next.config; this fallback covers rows
    // canonicalized after the last config sync, where the redirect degrades
    // to a 200 + meta refresh — keep an explicit canonical + noindex so
    // Google still gets an unambiguous dedup signal.
    return {
      alternates: { canonical: `${SITE_URL}/${lang}${detail.canonicalPath}` },
      robots: { index: false, follow: true },
    };
  }
  const path = `/${lang}/news/${category}/${item}`;
  return {
    title: detail.title,
    description: detail.summary,
    alternates: {
      canonical: `${SITE_URL}${path}`,
      languages: {
        en: `${SITE_URL}/en/news/${category}/${item}`,
        uk: `${SITE_URL}/uk/news/${category}/${item}`,
        'x-default': `${SITE_URL}/en/news/${category}/${item}`,
      },
    },
    openGraph: {
      title: detail.title,
      description: detail.summary,
      type: 'article',
      url: `${SITE_URL}${path}`,
      publishedTime: detail.publishedAt ?? undefined,
      // og:image is the branded card from opengraph-image.tsx in this segment
      // (Next includes it automatically): a unique AI illustration per item +
      // brand overlay, generated by the pipeline — never the raw source image.
    },
    ...socialMeta({
      title: detail.title,
      description: detail.summary,
      path,
      lang,
      type: 'article',
    }),
  };
}

export default async function ItemPage({ params }: { params: Promise<Params> }) {
  const { lang: raw, category, item } = await params;
  if (!isLang(raw)) notFound();
  const lang: Lang = raw;

  const detail = await getNewsItem(category, item, lang);
  if (!detail) notFound();
  if (detail.canonicalPath) permanentRedirect(`/${lang}${detail.canonicalPath}`);
  const t = getStrings(lang);
  const pagePath = `/${lang}/news/${category}/${item}`;

  const conceptIndex = await getConceptNameIndex();
  const toolLinks = detail.tools.map((name) => {
    const slug = conceptIndex.get(name.toLowerCase());
    return {
      name,
      href: slug ? `/${lang}/concepts/${slug}` : null,
    };
  });

  const [related, adjacent] = await Promise.all([
    detail.categorySlug != null
      ? getRelatedStories(lang, detail.categorySlug, detail.id)
      : Promise.resolve([]),
    getAdjacentStories(detail.briefId, detail.rank, lang),
  ]);

  const crumbs = [
    { label: t.news.breadcrumbHome, href: `/${lang}` },
    { label: t.nav.news, href: `/${lang}/news` },
    ...(detail.categorySlug
      ? [
          {
            label: detail.categoryName ?? detail.categorySlug,
            href: `/${lang}/category/${detail.categorySlug}`,
          },
        ]
      : []),
    { label: detail.title },
  ];

  const articleBody = detail.bodyMd
    ? markdownToPlainText(detail.bodyMd)
    : detail.deepDive || detail.summary;

  // The article itself shows the original full-frame visual. The branded card is
  // reserved for social/structured-data surfaces, where the typography overlay is
  // intentional rather than competing with the page's real HTML headline.
  const heroImage = detail.cardImageUrl ?? detail.imageUrl;
  // The branded card (illustration + masthead + headline + wordmark), rendered by
  // opengraph-image.tsx in this segment, remains the share/structured-data image.
  const brandCard = `${pagePath}/opengraph-image`;

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'NewsArticle',
        headline: detail.title,
        description: detail.summary,
        articleBody,
        image: [`${SITE_URL}${brandCard}`],
        datePublished: detail.publishedAt ?? detail.briefDate,
        dateModified: detail.publishedAt ?? detail.briefDate,
        inLanguage: lang,
        isAccessibleForFree: true,
        url: `${SITE_URL}${pagePath}`,
        author: authorNode(lang),
        publisher: publisherNode(),
        mainEntityOfPage: `${SITE_URL}${pagePath}`,
        ...(detail.citations.length > 0 || detail.sourceUrl
          ? {
              citation:
                detail.citations.length > 0
                  ? detail.citations.map((c) => ({
                      '@type': 'CreativeWork',
                      name: c.title || c.url,
                      url: c.url,
                    }))
                  : [{ '@type': 'CreativeWork', name: detail.sourceName ?? detail.sourceUrl }],
            }
          : {}),
      },
      breadcrumbJsonLd(crumbs, SITE_URL),
    ],
  };

  const videoId = youtubeVideoId(detail.youtubeUrl);

  const impactLabels = { low: t.impactLow, medium: t.impactMedium, high: t.impactHigh };

  return (
    <div className="max-w-page px-gutter mx-auto w-full flex-1 py-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="max-w-reading mx-auto">
        <Breadcrumbs items={crumbs} />
      </div>

      <article>
        <ItemEngagementTracker id={detail.id} slug={item} lang={lang} />

        <header className="max-w-reading mx-auto mb-8">
          <div className="mb-4 flex flex-wrap items-center gap-3">
            <CategoryBadge
              slug={detail.categorySlug}
              name={detail.categoryName}
              color={detail.categoryColor}
              size="md"
            />
            {detail.impactLevel && (
              <span className="text-muted text-xs font-semibold uppercase">
                {t.impactLabel}: {impactLabels[detail.impactLevel]}
              </span>
            )}
          </div>
          <h1 className="text-3xl leading-tight break-words sm:text-5xl">{detail.title}</h1>
          {detail.summary && (
            <p className="text-muted mt-4 text-lg leading-relaxed">{detail.summary}</p>
          )}
          {detail.sourceName && <p className="text-muted mt-4 text-sm">{detail.sourceName}</p>}
          <div className="mt-4">
            <Byline
              lang={lang}
              initials={EDITOR_NAME.split(' ')
                .map((part) => part[0])
                .join('')}
              authorName={EDITOR_NAME}
              role={EDITOR_ROLE[lang]}
              publishedAt={detail.briefDate}
              minutes={detail.readMinutes}
              hasAiDisclosure
            />
          </div>
        </header>

        <div className="max-w-reading mx-auto mb-8">
          {heroImage ? (
            <figure className="border-line bg-surface relative m-0 aspect-video overflow-hidden rounded-xl border">
              <Image
                src={heroImage}
                alt={detail.title}
                width={1280}
                height={720}
                preload
                sizes="(max-width: 47.5rem) 100vw, 42.5rem"
                className="h-full w-full object-contain"
              />
            </figure>
          ) : (
            <CategoryBanner
              name={detail.categoryName ?? 'AI'}
              slug={detail.categorySlug}
              color={detail.categoryColor}
              icon={detail.categoryIcon}
              motif={detail.rank}
              videoBadge={detail.hasVideo}
              videoLabel={t.landing.watchVideo}
            />
          )}
        </div>

        {videoId && (
          <div className="max-w-reading mx-auto mb-8">
            <VideoFacade
              videoId={videoId}
              thumbnailUrl={`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`}
              title={detail.title}
              lang={lang}
            />
          </div>
        )}

        <div className={styles.layout}>
          <aside
            className={styles.tools}
            aria-label={lang === 'uk' ? 'Дії з матеріалом' : 'Story tools'}
          >
            <ItemShareBar lang={lang} pageUrl={pagePath} title={detail.title} postId={detail.id} />
          </aside>
          <div className={styles.body}>
            <StoryBody lang={lang} detail={detail} toolLinks={toolLinks} />

            {detail.sourceUrl && (
              <a
                href={detail.sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="rounded-card border-line bg-surface text-text hover:border-accent mt-6 inline-flex items-center gap-2 border px-3.5 py-2.5 text-[0.88rem] no-underline transition"
              >
                {t.itemSource}: <strong>{detail.sourceName ?? t.readOriginal}</strong>
                <ExternalLinkIcon size={14} />
              </a>
            )}

            {(adjacent.prev || adjacent.next) && (
              <nav
                aria-label={`${t.prevStory} / ${t.nextStory}`}
                className="mt-8 grid gap-2.5 sm:grid-cols-2"
              >
                {adjacent.prev ? (
                  <Link
                    href={adjacent.prev.href}
                    className="rounded-card border-line bg-surface hover:border-accent block border p-3.5 no-underline transition"
                  >
                    <span className="text-faint text-2xs mb-1 block tracking-[0.06em] uppercase">
                      ← {t.prevStory}
                    </span>
                    <span className="text-text text-[0.92rem] leading-snug font-semibold break-words">
                      {adjacent.prev.title}
                    </span>
                  </Link>
                ) : (
                  <span aria-hidden className="hidden sm:block" />
                )}
                {adjacent.next && (
                  <Link
                    href={adjacent.next.href}
                    className="rounded-card border-line bg-surface hover:border-accent block border p-3.5 text-right no-underline transition"
                  >
                    <span className="text-faint text-2xs mb-1 block tracking-[0.06em] uppercase">
                      {t.nextStory} →
                    </span>
                    <span className="text-text text-[0.92rem] leading-snug font-semibold break-words">
                      {adjacent.next.title}
                    </span>
                  </Link>
                )}
              </nav>
            )}
          </div>
        </div>
      </article>

      {related.length > 0 && (
        <section className="max-w-reading mx-auto mt-12" aria-labelledby="related-title">
          <h2 id="related-title" className="mb-4 text-xl">
            {t.itemRelated}
          </h2>
          <ul className="m-0 grid list-none gap-2.5 p-0">
            {related.slice(0, 3).map((story) => (
              <li key={story.id}>
                <Link
                  href={story.href}
                  className="rounded-card border-line bg-surface hover:border-accent flex items-center gap-3 border p-3.5 no-underline transition"
                >
                  <CategoryBadge
                    slug={story.categorySlug}
                    name={story.categoryName}
                    color={story.categoryColor}
                  />
                  <span className="min-w-0 flex-1 font-serif text-base font-semibold text-[color:inherit]">
                    {story.title}
                  </span>
                  <ArrowRight size={16} className="text-faint shrink-0" />
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section className="max-w-reading mx-auto mt-12">
        <NewsletterForm lang={lang} variant="inline" placement="item-page" />
      </section>
    </div>
  );
}
