import Image from 'next/image';
import Link from 'next/link';
import { notFound, permanentRedirect } from 'next/navigation';
import type { Metadata } from 'next';
import { isLang, SITE_URL, type Lang } from '@/lib/site';
import { authorNode, publisherNode } from '@/lib/schema';
import { getStrings } from '@/lib/i18n';
import { getConceptNameIndex } from '@/lib/concepts';
import { markdownToPlainText } from '@/lib/markdown';
import {
  getAdjacentStories,
  getNewsItem,
  getPublishedItemPaths,
  getRelatedStories,
  youtubeVideoId,
} from '@/lib/items';
import { Breadcrumbs, breadcrumbJsonLd } from '@/components/breadcrumbs';
import { Byline } from '@/components/byline';
import { AiDisclosureNote } from '@/components/ai-disclosure-note';
import { CategoryBadge } from '@/components/home/category-badge';
import { CategoryBanner } from '@/components/category-banner';
import { StoryBody } from '@/components/story-body';
import { ItemShareBar } from '@/components/item-share-bar';
import { ItemEngagementTracker } from '@/components/item-engagement-tracker';
import { NewsletterBand } from '@/components/home/newsletter-band';
import { Reveal } from '@/components/reveal';
import { ArrowRight, ClockIcon, ExternalLinkIcon, PlayIcon } from '@/components/icons';

// 24 h: item content is fixed at publish; the editor-take edit revalidates the
// exact item path on-demand (see api/telegram handleEditorTake), so takes still
// appear immediately. The old 30 min window mostly fed bot-driven regenerations.
export const revalidate = 86400;

type Params = { lang: string; category: string; item: string };

export async function generateStaticParams() {
  return getPublishedItemPaths();
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { lang, category, item } = await params;
  if (!isLang(lang)) return {};
  const detail = await getNewsItem(category, item, lang);
  if (!detail) return {};
  if (detail.canonicalPath) {
    // The page normally 308s via next.config; this fallback covers rows
    // canonicalized after the last config sync, where the redirect degrades
    // to a 200 + meta refresh — keep an explicit canonical + noindex so
    // Google still gets an unambiguous dedup signal.
    return {
      alternates: { canonical: `${SITE_URL}/${lang}${detail.canonicalPath}` },
      robots: { index: false, follow: true },
    };
  }
  const path = `/${lang}/news/${category}/${item}`;
  return {
    title: detail.title,
    description: detail.summary,
    alternates: {
      canonical: `${SITE_URL}${path}`,
      languages: {
        en: `${SITE_URL}/en/news/${category}/${item}`,
        uk: `${SITE_URL}/uk/news/${category}/${item}`,
        'x-default': `${SITE_URL}/en/news/${category}/${item}`,
      },
    },
    openGraph: {
      title: detail.title,
      description: detail.summary,
      type: 'article',
      url: `${SITE_URL}${path}`,
      publishedTime: detail.publishedAt ?? undefined,
      // og:image is the branded card from opengraph-image.tsx in this segment
      // (Next includes it automatically): a unique AI illustration per item +
      // brand overlay, generated by the pipeline — never the raw source image.
    },
  };
}

export default async function ItemPage({ params }: { params: Promise<Params> }) {
  const { lang: raw, category, item } = await params;
  if (!isLang(raw)) notFound();
  const lang: Lang = raw;

  const detail = await getNewsItem(category, item, lang);
  if (!detail) notFound();
  if (detail.canonicalPath) permanentRedirect(`/${lang}${detail.canonicalPath}`);
  const t = getStrings(lang);
  const tNews = getStrings(lang).news;
  const pagePath = `/${lang}/news/${category}/${item}`;

  const dateLabel = new Intl.DateTimeFormat(lang === 'uk' ? 'uk-UA' : 'en-US', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date(`${detail.briefDate}T00:00:00`));

  const conceptIndex = await getConceptNameIndex();
  const toolLinks = detail.tools.map((name) => {
    const slug = conceptIndex.get(name.toLowerCase());
    return {
      name,
      href: slug ? `/${lang}/concepts/${slug}` : null,
    };
  });

  const [related, adjacent] = await Promise.all([
    detail.categorySlug != null
      ? getRelatedStories(lang, detail.categorySlug, detail.id)
      : Promise.resolve([]),
    getAdjacentStories(detail.briefId, detail.rank, lang),
  ]);

  const crumbs = [
    { label: t.news.breadcrumbHome, href: `/${lang}` },
    { label: t.nav.news, href: `/${lang}/news` },
    ...(detail.categorySlug
      ? [
          {
            label: detail.categoryName ?? detail.categorySlug,
            href: `/${lang}/category/${detail.categorySlug}`,
          },
        ]
      : []),
    { label: detail.title },
  ];

  const articleBody = detail.bodyMd
    ? markdownToPlainText(detail.bodyMd)
    : detail.deepDive || detail.summary;

  // Prefer the generated brand card (always present) over the raw source image.
  const heroImage = detail.cardImageUrl ?? detail.imageUrl;
  // The full branded card (illustration + masthead + headline + wordmark),
  // rendered by opengraph-image.tsx in this segment — used as the article cover.
  const brandCard = `${pagePath}/opengraph-image`;

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'NewsArticle',
        headline: detail.title,
        description: detail.summary,
        articleBody,
        image: [`${SITE_URL}${brandCard}`],
        datePublished: detail.publishedAt ?? detail.briefDate,
        dateModified: detail.publishedAt ?? detail.briefDate,
        inLanguage: lang,
        isAccessibleForFree: true,
        url: `${SITE_URL}${pagePath}`,
        author: authorNode(lang),
        publisher: publisherNode(),
        mainEntityOfPage: `${SITE_URL}${pagePath}`,
        ...(detail.citations.length > 0 || detail.sourceUrl
          ? {
              citation:
                detail.citations.length > 0
                  ? detail.citations.map((c) => ({
                      '@type': 'CreativeWork',
                      name: c.title || c.url,
                      url: c.url,
                    }))
                  : [{ '@type': 'CreativeWork', name: detail.sourceName ?? detail.sourceUrl }],
            }
          : {}),
      },
      breadcrumbJsonLd(crumbs, SITE_URL),
    ],
  };

  const videoId = youtubeVideoId(detail.youtubeUrl);

  const color = detail.categoryColor ?? '#888888';

  return (
    <div className="mx-auto w-full max-w-[760px] flex-1 px-6 py-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <Breadcrumbs items={crumbs} />

      <article>
        <ItemEngagementTracker id={detail.id} slug={item} lang={lang} />

        <div className="mb-4">
          <CategoryBadge name={detail.categoryName} color={detail.categoryColor} size="md" />
        </div>

        {/* The branded cover card below carries the visible headline; keep a
            real h1 for SEO + screen readers without duplicating it on screen. */}
        <h1 className="sr-only">{detail.title}</h1>

        <div className="text-faint mb-4 flex flex-wrap items-center gap-2 text-[0.82rem]">
          {detail.sourceName && <span>{detail.sourceName}</span>}
          {detail.sourceName && (
            <span aria-hidden className="text-faint">
              ·
            </span>
          )}
          <span>{dateLabel}</span>
          <span aria-hidden>·</span>
          <span className="inline-flex items-center gap-1">
            <ClockIcon size={13} /> {detail.readMinutes} {tNews.readMin}
          </span>
          {detail.hasVideo && (
            <>
              <span aria-hidden>·</span>
              <span
                className="cat-fg inline-flex items-center gap-1 font-semibold"
                style={{ '--cat-color': color } as React.CSSProperties}
              >
                <PlayIcon size={13} /> {t.landing.watchVideo}
              </span>
            </>
          )}
        </div>

        <div className="mb-6 flex flex-wrap items-center gap-3">
          <Byline lang={lang} updated={detail.briefDate} />
          <AiDisclosureNote lang={lang} />
        </div>

        <Reveal>
          <div className="mb-6">
            {heroImage ? (
              <figure className="border-border relative m-0 aspect-[1200/630] overflow-hidden rounded-xl border">
                <Image
                  src={brandCard}
                  alt={detail.title}
                  fill
                  priority
                  sizes="(max-width: 760px) 100vw, 760px"
                  className="object-cover"
                />
              </figure>
            ) : (
              <CategoryBanner
                name={detail.categoryName ?? 'AI'}
                color={color}
                icon={detail.categoryIcon}
                motif={detail.rank}
                videoBadge={detail.hasVideo}
                videoLabel={t.landing.watchVideo}
              />
            )}
          </div>
        </Reveal>

        <p className="mb-5 text-[1.1rem] leading-[1.7]">{detail.summary}</p>

        {videoId && (
          <div className="border-border relative mb-6 aspect-video overflow-hidden rounded-xl border">
            <iframe
              src={`https://www.youtube-nocookie.com/embed/${videoId}`}
              title={detail.title}
              loading="lazy"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="absolute inset-0 h-full w-full border-0"
            />
          </div>
        )}

        <StoryBody lang={lang} detail={detail} toolLinks={toolLinks} />

        {detail.sourceUrl && (
          <a
            href={detail.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-card border-border bg-surface text-text mt-6 inline-flex items-center gap-2 border px-3.5 py-2.5 text-[0.88rem] no-underline transition hover:border-accent"
          >
            {t.itemSource}: <strong>{detail.sourceName ?? t.readOriginal}</strong>
            <ExternalLinkIcon size={14} />
          </a>
        )}

        <ItemShareBar lang={lang} pageUrl={pagePath} title={detail.title} postId={detail.id} />

        {(adjacent.prev || adjacent.next) && (
          <nav
            aria-label={`${t.prevStory} / ${t.nextStory}`}
            className="mt-8 grid gap-2.5 sm:grid-cols-2"
          >
            {adjacent.prev ? (
              <Link
                href={adjacent.prev.href}
                className="rounded-card border-border bg-surface hover:border-accent block border p-3.5 no-underline transition"
              >
                <span className="text-faint mb-1 block text-[0.72rem] tracking-[0.06em] uppercase">
                  ← {t.prevStory}
                </span>
                <span className="text-text text-[0.92rem] font-semibold leading-snug break-words">
                  {adjacent.prev.title}
                </span>
              </Link>
            ) : (
              <span aria-hidden className="hidden sm:block" />
            )}
            {adjacent.next && (
              <Link
                href={adjacent.next.href}
                className="rounded-card border-border bg-surface hover:border-accent block border p-3.5 text-right no-underline transition"
              >
                <span className="text-faint mb-1 block text-[0.72rem] tracking-[0.06em] uppercase">
                  {t.nextStory} →
                </span>
                <span className="text-text text-[0.92rem] font-semibold leading-snug break-words">
                  {adjacent.next.title}
                </span>
              </Link>
            )}
          </nav>
        )}
      </article>

      {related.length > 0 && (
        <section className="mt-12" aria-labelledby="related-title">
          <h2 id="related-title" className="mb-4 text-xl">
            {t.itemRelated}
          </h2>
          <ul className="m-0 grid list-none gap-2.5 p-0">
            {related.map((story) => (
              <li key={story.id}>
                <Link
                  href={story.href}
                  className="rounded-card border-border bg-surface hover:border-accent flex items-center gap-3 border p-3.5 no-underline transition"
                >
                  <CategoryBadge name={story.categoryName} color={story.categoryColor} />
                  <span className="font-serif min-w-0 flex-1 text-base font-semibold text-[color:inherit]">
                    {story.title}
                  </span>
                  <ArrowRight size={16} className="text-faint shrink-0" />
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section className="mt-12">
        <NewsletterBand lang={lang} embedded placement="item-page" />
      </section>
    </div>
  );
}
