import { expect, test } from '@playwright/test';
import baseline from './fixtures/policy-text.baseline.json';
import seoBaseline from './fixtures/seo-contract.baseline.json';
import { compareSeoSnapshots, parseSeoHtml, type SeoSnapshot } from '../src/lib/seo-contract';
import { expectedSiteUrl } from '../scripts/e2e-server-url';

// Covered routes:
// /en/editorial-policy /en/ai-disclosure /en/privacy /en/terms
// /uk/editorial-policy /uk/ai-disclosure /uk/privacy /uk/terms

for (const document of baseline.routes) {
  test(`${document.path}: verbatim document, navigation and SEO`, async ({ page, request }) => {
    await page.goto(document.path);
    const article = page.getByTestId('policy-document');
    await expect(article).toBeVisible();
    // Compare the document itself; the owner explicitly excluded new navigation.
    const blocks = await article.evaluate((element) => {
      const copy = element.cloneNode(true);
      if (!(copy instanceof Element)) throw new Error('Missing policy document');
      copy.querySelectorAll('nav, aside').forEach((navigation) => navigation.remove());
      return Array.from(copy.querySelectorAll('h1, h2, p'), (block) => block.textContent ?? '');
    });
    expect(blocks.map((text) => text.replace(/\s+/g, ' ').trim())).toEqual(document.blocks);
    await expect(page.locator('main h1')).toHaveCount(1);

    const lang = document.path.split('/')[1];
    const policies = page.getByRole('navigation', {
      name: lang === 'uk' ? 'Політики' : 'Policies',
      exact: true,
    });
    await expect(policies.getByRole('link')).toHaveCount(4);
    await expect(policies.locator('[aria-current="page"]')).toHaveCount(1);
    await expect(policies.locator('[aria-current="page"]')).toHaveAttribute('href', document.path);
    await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true })).toBeVisible();

    const toc = page.getByRole('navigation', {
      name: lang === 'uk' ? 'Зміст' : 'Contents',
      exact: true,
    });
    const headings = article.locator('h2');
    await expect(toc.getByRole('link')).toHaveCount(await headings.count());
    for (const link of await toc.getByRole('link').all()) {
      const href = await link.getAttribute('href');
      expect(href).toMatch(/^#/);
      const heading = article.locator(`${href} h2`);
      await expect(heading).toHaveText(await link.innerText());
    }
    await toc.getByRole('link').first().click();
    await expect(page).toHaveURL(/#.+$/);
    if (document.path.endsWith('/editorial-policy')) {
      await expect(article.locator('time')).toHaveCount(0);
    } else {
      await expect(article.locator('time')).toHaveAttribute('datetime', '2026-06-01');
    }

    // This checked-in fixture was generated by parseSeoHtml; JSON inference creates optional OG keys.
    const saved = seoBaseline.routes.find((route) => route.path === document.path) as
      SeoSnapshot | undefined;
    expect(saved).toBeDefined();
    if (!saved) throw new Error(`Missing SEO baseline: ${document.path}`);
    const siteUrl = expectedSiteUrl();
    const expected = {
      ...saved,
      canonical: saved.canonical?.replace('https://aitodaybrief.com', siteUrl) ?? null,
      hreflang: Object.fromEntries(
        Object.entries(saved.hreflang).map(([key, url]) => [
          key,
          url.replace('https://aitodaybrief.com', siteUrl),
        ]),
      ),
    };
    const response = await request.get(document.path);
    const current = parseSeoHtml(await response.text(), document.path, response.status());
    expect(compareSeoSnapshots(expected, current)).toEqual({ errors: [], warnings: [] });
    expect(current.title).toBe(saved.title);
    expect(current.description).toBe(saved.description);
    expect(current.openGraph['og:title']).toBe(saved.openGraph['og:title']);
    expect(current.openGraph['og:description']).toBe(saved.openGraph['og:description']);

    // Exercise a real cross-document link, preserving the current locale.
    const target = policies.locator('a:not([aria-current])').first();
    const destination = await target.getAttribute('href');
    await target.click();
    await expect(page).toHaveURL(new RegExp(`${destination}(?:\\?.*)?$`));
  });
}
