import { ImageResponse } from 'next/og';
import { duotoneDataUri, paletteFromCategory } from '@/lib/card/duotone';
import { getBriefItem } from '@/lib/items';
import { isLang, SITE_NAME, SITE_URL } from '@/lib/site';

export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';
export const alt = SITE_NAME;

// Fonts live in /public and are fetched over https — this route runs on the
// edge runtime (next/og default), where fetch(file://) and fs are unavailable.
const FONT = (file: string) => fetch(`${SITE_URL}/fonts/${file}`).then((r) => r.arrayBuffer());

/**
 * Branded share / OG card: a unique per-item AI illustration (generated by the
 * pipeline into `card_image_url`) under the constant brand overlay — category
 * masthead, headline, "AI Today Brief" wordmark + signal mark. When no image was
 * generated, a category-tinted duotone fallback is drawn instead, so every item
 * always has an on-brand card.
 */
export default async function OgImage({
  params,
}: {
  params: Promise<{ lang: string; brief: string; item: string }>;
}) {
  const { lang, brief, item } = await params;
  const detail = isLang(lang) ? await getBriefItem(brief, item, lang) : null;

  const title = detail?.title ?? SITE_NAME;
  const category = detail?.categoryName ?? 'AI';
  const accent = detail?.categoryColor ?? '#f0c040';
  const slug = detail?.itemSlug ?? 'card';

  const background =
    detail?.cardImageUrl ??
    duotoneDataUri({ seed: slug, palette: paletteFromCategory(accent) });

  const dateLabel = detail?.briefDate
    ? new Intl.DateTimeFormat(lang === 'uk' ? 'uk-UA' : 'en-US', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      }).format(new Date(`${detail.briefDate}T00:00:00`))
    : '';

  const titleSize = title.length > 84 ? 46 : title.length > 56 ? 52 : 60;

  const [interLatin, interCyr, fraunces] = await Promise.all([
    FONT('inter-latin-700.woff'),
    FONT('inter-cyrillic-700.woff'),
    FONT('fraunces-latin-600.woff'),
  ]);

  return new ImageResponse(
    (
      <div style={{ position: 'relative', display: 'flex', width: '100%', height: '100%', backgroundColor: '#0b0b0b' }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={background}
          alt=""
          width={1200}
          height={630}
          style={{ position: 'absolute', top: 0, left: 0, width: 1200, height: 630, objectFit: 'cover' }}
        />
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: 1200,
            height: 630,
            background:
              'linear-gradient(180deg, rgba(11,11,11,0.55) 0%, rgba(11,11,11,0.12) 24%, rgba(11,11,11,0.12) 42%, rgba(11,11,11,0.74) 80%, rgba(11,11,11,0.95) 100%)',
          }}
        />
        <div
          style={{
            position: 'relative',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            width: '100%',
            height: '100%',
            padding: '56px 64px',
            color: '#ffffff',
            fontFamily: 'Inter',
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
              <div style={{ width: 16, height: 16, borderRadius: 9999, background: accent }} />
              <div
                style={{
                  fontSize: 24,
                  fontWeight: 700,
                  letterSpacing: 3,
                  textTransform: 'uppercase',
                  color: accent,
                }}
              >
                {category}
              </div>
            </div>
            <div style={{ fontSize: 24, color: '#dcdcdc' }}>{dateLabel}</div>
          </div>

          <div
            style={{
              fontSize: titleSize,
              fontWeight: 700,
              lineHeight: 1.13,
              maxWidth: 1010,
              display: 'block',
              lineClamp: 3,
            }}
          >
            {title}
          </div>

          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              borderTop: '2px solid rgba(255,255,255,0.2)',
              paddingTop: 22,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'flex-end', gap: 16 }}>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'baseline',
                  fontSize: 31,
                  fontWeight: 600,
                  fontFamily: 'Fraunces',
                  color: '#ffffff',
                }}
              >
                <span>AI Today</span>
                <span style={{ color: '#f0c040', marginLeft: 8 }}>Brief</span>
              </div>
              <div style={{ display: 'flex', alignItems: 'flex-end', gap: 3, paddingBottom: 6 }}>
                {[6, 11, 15, 21].map((h) => (
                  <div key={h} style={{ width: 4, height: h, borderRadius: 2, background: '#f0c040' }} />
                ))}
              </div>
            </div>
            <div style={{ fontSize: 23, color: '#c4cbd6' }}>aitodaybrief.com</div>
          </div>
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        { name: 'Inter', data: interLatin, weight: 700, style: 'normal' },
        { name: 'Inter Cyrillic', data: interCyr, weight: 700, style: 'normal' },
        { name: 'Fraunces', data: fraunces, weight: 600, style: 'normal' },
      ],
    },
  );
}
