-- Nine canonical categories chosen to match the reader profile from
-- rank.ts and the summarize prompt. Each story slots into exactly one;
-- secondary tags live in tools_mentioned. Colours are hand-picked to be
-- visually distinct on the dark theme.

INSERT INTO public.categories (slug, name_en, name_uk, description_en, description_uk, color, position) VALUES
  ('tools-and-releases',
    'Tools & releases', 'Інструменти й релізи',
    'New features, version bumps and hidden capabilities in Claude Code, Cursor, Codex, Gemini, Copilot and other agentic IDEs.',
    'Нові фічі, оновлення версій і приховані можливості в Claude Code, Cursor, Codex, Gemini, Copilot та інших agentic IDE.',
    '#47E4D3', 10),
  ('tutorials-and-guides',
    'Tutorials & guides', 'Гайди й туторіали',
    'Hands-on walkthroughs, cheatsheets, prompt recipes and step-by-step playbooks for AI dev workflows.',
    'Hands-on проходження, cheatsheet-и, prompt-рецепти і покрокові плейбуки для AI dev-воркфлоу.',
    '#F4C26B', 20),
  ('optimization',
    'Token & cost optimization', 'Оптимізація токенів',
    'Prompt caching, context window engineering, token budgets, batching — anything that drops your LLM bill.',
    'Prompt caching, керування context window, токен-бюджети, batching — все, що знижує LLM-рахунок.',
    '#9CD66F', 30),
  ('agents-and-mcp',
    'Agents & MCP', 'Агенти й MCP',
    'Building, orchestrating and connecting agents — MCP servers, Claude Agent SDK, multi-agent systems.',
    'Побудова, оркестрація та підключення агентів — MCP-сервери, Claude Agent SDK, мульти-агентні системи.',
    '#B58CF7', 40),
  ('vibe-coding',
    'Vibe coding workflow', 'Vibe coding',
    'Skills, hooks, slash commands, subagents, testing patterns and editorial rules for AI-assisted coding sessions.',
    'Skills, hooks, slash-команди, sub-агенти, патерни тестування та правила для AI-assisted coding сесій.',
    '#5BC9F0', 50),
  ('creative-ai',
    'Creative AI', 'Креативний AI',
    'Image, video, animation, audio and text content generation tools relevant for developers and indie creators.',
    'Інструменти генерації зображень, відео, анімації, аудіо та текстового контенту для розробників і indie-творців.',
    '#FF8FA3', 60),
  ('local-llms',
    'Local LLMs', 'Локальні LLM',
    'Self-hosted inference, GGUF / llama.cpp, Ollama, hardware setups and privacy-first AI stacks.',
    'Self-hosted інференс, GGUF / llama.cpp, Ollama, апаратні збірки та privacy-first AI-стеки.',
    '#8A8FFF', 70),
  ('career-and-money',
    'Career & monetisation', 'Карʼєра й заробіток',
    'Freelance leads, indie-SaaS plays, free certifications, internships and realistic monetisation paths for AI-native devs.',
    'Freelance-ліди, indie-SaaS, безкоштовні сертифікати, стажування та реалістичні шляхи монетизації для AI-native розробників.',
    '#FF9B57', 80),
  ('models-and-research',
    'Models & research', 'Моделі й дослідження',
    'Model releases, benchmarks and research findings with practical implications for everyday building.',
    'Релізи моделей, бенчмарки та research-результати з практичними наслідками для щоденної роботи.',
    '#D49CFF', 90)
ON CONFLICT (slug) DO UPDATE SET
  name_en        = EXCLUDED.name_en,
  name_uk        = EXCLUDED.name_uk,
  description_en = EXCLUDED.description_en,
  description_uk = EXCLUDED.description_uk,
  color          = EXCLUDED.color,
  position       = EXCLUDED.position;
