-- Move daily briefs from /:lang/:date URLs onto title-based slugs:
--   /:lang/cursor-2-0-and-token-tactics  (brief)
--   /:lang/cursor-2-0-and-token-tactics/claude-prompt-cache  (item)
--
-- Why: bare dates in the URL are weak SEO signal — Google sees "27 May 2026"
-- as a date, not a topic. Slug-based URLs surface the brief's topic in both
-- the address bar and any backlink anchor text. Dates remain as a filter on
-- /news, just no longer in the navigation path.
--
-- Slug uniqueness is enforced globally (one /uk/foo can only mean one brief)
-- via a partial unique index. New briefs generated by summarize.ts get their
-- slug on insert; legacy rows get backfilled here.

ALTER TABLE public.briefs
  ADD COLUMN IF NOT EXISTS slug text;

-- Partial index so NULL rows from before the column existed don't collide.
CREATE UNIQUE INDEX IF NOT EXISTS briefs_slug_uniq
  ON public.briefs (slug)
  WHERE slug IS NOT NULL;

-- Backfill existing rows from title_en. Strategy:
--   1. Lowercase + ASCII-fold (we approximate by stripping non-ASCII letters).
--   2. Replace non-alphanumeric runs with a single dash.
--   3. Trim leading/trailing dashes.
--   4. Truncate to 80 chars to avoid hostile-long URLs.
-- If two briefs collapse to the same slug, the unique index will reject the
-- second update — manual fix needed, but we only have a handful of legacy
-- rows so the risk is negligible.

UPDATE public.briefs
SET slug = (
  CASE WHEN trim(title_en) = '' THEN 'brief-' || to_char(date, 'YYYY-MM-DD')
       ELSE
         substring(
           regexp_replace(
             regexp_replace(lower(title_en), '[^a-z0-9]+', '-', 'g'),
             '^-+|-+$', '', 'g'
           )
           FROM 1 FOR 80
         )
  END
)
WHERE slug IS NULL;
